<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VendorTrack.Domain\VendorTrack.Domain.csproj" />
    <ProjectReference Include="..\VendorTrack.Data\VendorTrack.Data.csproj" />
    <ProjectReference Include="..\VendorTrack.Business\VendorTrack.Business.csproj" />
  </ItemGroup>
</Project>
